{
  "groups": [
    {
      "id": "gl",
      "name": "Language",
      "color": "#00000000",
      "borderColor": "#FFFFFFFF",
      "isExpanded": false
    },
    {
      "id": "source",
      "name": "Source",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    },
    {
      "id": "resolution",
      "name": "Resolution",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    },
    {
      "id": "video-tech",
      "name": "Video Tech",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    },
    {
      "id": "video-codec",
      "name": "Video Codec",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    },
    {
      "id": "bit-depth",
      "name": "Bit Depth",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    },
    {
      "id": "audio-tech",
      "name": "Audio Tech",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    },
    {
      "id": "audio-channels",
      "name": "Audio Channels",
      "color": "#00000000",
      "borderColor": "#00000000",
      "isExpanded": true
    }
  ],
  "filters": [
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-en",
      "imageURL": "https://files.catbox.moe/rc1k68.png",
      "isEnabled": true,
      "name": "🇬🇧",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(english|eng)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-es",
      "imageURL": "https://files.catbox.moe/dpgdsz.png",
      "isEnabled": true,
      "name": "🇪🇸",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(spanish|spa|esp|latino|lat)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-fr",
      "imageURL": "https://files.catbox.moe/tlsgr3.png",
      "isEnabled": true,
      "name": "🇫🇷",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(french|fra|fr|vf|vff|vfi|vf2|vfq|truefrench)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-de",
      "imageURL": "https://files.catbox.moe/pun90i.png",
      "isEnabled": true,
      "name": "🇩🇪",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(deu(?:tsch)?(?:land)?|ger(?:man)?|german)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-it",
      "imageURL": "https://files.catbox.moe/2k1nj1.png",
      "isEnabled": true,
      "name": "🇮🇹",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(italian|ita)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-pt-br",
      "imageURL": "https://files.catbox.moe/yt91v6.png",
      "isEnabled": true,
      "name": "🇧🇷",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(portuguese[ .\\-_]?brazil|pt[ .\\-_]?br|brazilian)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-pt-pt",
      "imageURL": "https://files.catbox.moe/utp37t.png",
      "isEnabled": true,
      "name": "🇵🇹",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(portuguese(?!(?:[ .\\-_]?brazil))|portuguese[ .\\-_]?(?:portugal|europe(?:an)?)|pt[ .\\-_]?pt)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-tr",
      "imageURL": "https://files.catbox.moe/gvu0en.png",
      "isEnabled": true,
      "name": "🇹🇷",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(turkish|tur)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-pl",
      "imageURL": "https://files.catbox.moe/bfo48w.png",
      "isEnabled": true,
      "name": "🇵🇱",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(polish|pol)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-uk",
      "imageURL": "https://files.catbox.moe/kph90l.png",
      "isEnabled": true,
      "name": "🇺🇦",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(ukrainian|ukr)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-id",
      "imageURL": "https://files.catbox.moe/pdo7ya.png",
      "isEnabled": true,
      "name": "🇮🇩",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(indonesian|ind)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-th",
      "imageURL": "https://files.catbox.moe/5oswaw.png",
      "isEnabled": true,
      "name": "🇹🇭",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(thai|tha)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-vi",
      "imageURL": "https://files.catbox.moe/qpbmmr.png",
      "isEnabled": true,
      "name": "🇻🇳",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(vietnamese|vie)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-ja",
      "imageURL": "https://files.catbox.moe/t648by.png",
      "isEnabled": true,
      "name": "🇯🇵",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(japanese|jap|jpn)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[぀-ゟ゠-ヿ]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-ko",
      "imageURL": "https://files.catbox.moe/o34nat.png",
      "isEnabled": true,
      "name": "🇰🇷",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(korean|kor)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[가-힯]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-zh",
      "imageURL": "https://files.catbox.moe/l5ofg6.png",
      "isEnabled": true,
      "name": "🇨🇳",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(chinese|chi|zho|mandarin|cantonese)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[一-鿿]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-hi",
      "imageURL": "https://files.catbox.moe/ejqdu2.png",
      "isEnabled": true,
      "name": "🇮🇳",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(hindi|hin)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[ऀ-ॿ]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-ar",
      "imageURL": "https://files.catbox.moe/ejhyfk.png",
      "isEnabled": true,
      "name": "🇸🇦",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(arabic|ara)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[؀-ۿ]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-ru",
      "imageURL": "https://files.catbox.moe/p79jj3.png",
      "isEnabled": true,
      "name": "🇷🇺",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(russian|rus)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[Ѐ-ӿ]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-el",
      "imageURL": "https://files.catbox.moe/pik7ab.png",
      "isEnabled": true,
      "name": "🇬🇷",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(greek|ellinika|hellenic|grec|ell|gre)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|$)|[\\u0370-\\u03FF\\u1F00-\\u1FFF]{3,}",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "borderColor": "#3eac9a",
      "groupId": "gl",
      "id": "l-mu",
      "imageURL": "https://files.catbox.moe/caqmea.png",
      "isEnabled": true,
      "name": "🌐",
      "pattern": "(?i)(?<![^\\s\\[(_\\-.,])(multi)(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]|\( )|(?<![^\\s\\[(_\\-.,])(dual[ .\\-_]?(?:audio|lang(?:uage)?|flac|ac3|aac2?))(?![ .\\-_]?sub(title)?s?)(?=[\\s\\)\\]_.\\-,]| \))",
      "tagColor": "#00000000",
      "tagStyle": "filled",
      "textColor": "#FFFFFF",
      "type": "filter"
    },
    {
      "id": "remux",
      "groupId": "source",
      "name": "REMUX",
      "pattern": "(?i)\\bremux\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/remux.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "blu-ray-disc",
      "groupId": "source",
      "name": "Blu-ray Disc",
      "pattern": "(?i)\\b(blu[\\s._-]?ray|bluray|bdrip|bdremux)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/blu_ray_disc.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "webdl",
      "groupId": "source",
      "name": "WEB-DL",
      "pattern": "(?i)\\b(web[\\s._-]?dl|webdl)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/WEBDL_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "webrip",
      "groupId": "source",
      "name": "WEBRip",
      "pattern": "(?i)\\b(web[\\s._-]?rip|webrip)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/WEBRip_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "hdtv",
      "groupId": "source",
      "name": "HDTV",
      "pattern": "(?i)\\bhdtv\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/HDTV_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dvd-rip",
      "groupId": "source",
      "name": "DVD RIP",
      "pattern": "(?i)\\b(dvd[\\s._-]?rip|dvdrip)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/DVD_RIP_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "4k-ultra-hd",
      "groupId": "resolution",
      "name": "4K Ultra HD",
      "pattern": "(?i)\\b(4k|2160p|uhd|ultra\\s*hd)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/4k_ultra_hd.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "1080p-full-hd",
      "groupId": "resolution",
      "name": "1080p Full HD",
      "pattern": "(?i)\\b(1080p|fhd|full\\s*hd)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/1080p_full_hd.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "720p-hd",
      "groupId": "resolution",
      "name": "720p HD",
      "pattern": "(?i)\\b720p\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/720p_hd.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "480p-sd",
      "groupId": "resolution",
      "name": "480p SD",
      "pattern": "(?i)\\b480p\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/480p_sd.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dolby-vision",
      "groupId": "video-tech",
      "name": "Dolby Vision",
      "pattern": "(?i)\\b(dolby\\s*vision|dovi|dv)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dolby_vision.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "hdr10-plus",
      "groupId": "video-tech",
      "name": "HDR10+",
      "pattern": "(?i)\\b(hdr10\\+|hdr10\\s*plus\\b|hdr\\s*10\\s*\\+)",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/hdr10_plus.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "hdr10",
      "groupId": "video-tech",
      "name": "HDR10",
      "pattern": "(?i)\\b(hdr10|hdr\\s*10)\\b(?!\\s*\\+|\\s*plus)",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/hdr10.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "hdr",
      "groupId": "video-tech",
      "name": "HDR",
      "pattern": "(?i)\\bhdr\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/hdr.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "sdr",
      "groupId": "video-tech",
      "name": "SDR",
      "pattern": "(?i)\\bsdr\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/SDR_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "imax-enhanced",
      "groupId": "video-tech",
      "name": "IMAX Enhanced",
      "pattern": "(?i)\\b(imax[\\s._-]*enhanced)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/imax_enhanced.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "imax",
      "groupId": "video-tech",
      "name": "IMAX",
      "pattern": "(?i)\\b(imax)\\b(?![\\s._-]*enhanced)",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/imax.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "hevc",
      "groupId": "video-codec",
      "name": "HEVC",
      "pattern": "(?i)\\b(hevc|h[\\s._-]?265|x265)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/HEVC_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "avc",
      "groupId": "video-codec",
      "name": "AVC",
      "pattern": "(?i)\\b(avc|h[\\s._-]?264|x264)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/AVC_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "10bit",
      "groupId": "bit-depth",
      "name": "10Bit",
      "pattern": "(?i)\\b(10[\\s._-]?bit|10b|hi10p)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/10Bit_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "8bit",
      "groupId": "bit-depth",
      "name": "8Bit",
      "pattern": "(?i)\\b(8[\\s._-]?bit|8b)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/8Bit_transparent_4x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dolby-atmos",
      "groupId": "audio-tech",
      "name": "Dolby Atmos",
      "pattern": "(?i)\\b(dolby\\s*atmos|atmos)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dolby_atmos.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "truehd",
      "groupId": "audio-tech",
      "name": "TrueHD",
      "pattern": "(?i)\\b(truehd|true\\s*hd|dolby\\s*truehd)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/truehd.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dolby-digital-plus",
      "groupId": "audio-tech",
      "name": "Dolby Digital Plus",
      "pattern": "(?i)\\b(ddp[\\s._-]*[0-9][\\s._-]*[0-9]|ddp|dd\\+|dolby[\\s._-]*digital[\\s._-]*plus|e-?ac-?3)(?![a-z])",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dolby_digital_plus.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dolby-digital",
      "groupId": "audio-tech",
      "name": "Dolby Digital",
      "pattern": "(?i)\\b(dd[\\s._-]*[0-9][\\s._-]*[0-9]|dd|dolby[\\s._-]*digital|ac-?3)(?![\\s._-]*plus|\\+|p|[a-z])",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dolby_digital.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dts-x",
      "groupId": "audio-tech",
      "name": "DTS:X",
      "pattern": "(?i)\\b(dts[:\\s._-]*x)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dts_x.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dts-hd-master-audio",
      "groupId": "audio-tech",
      "name": "DTS-HD Master Audio",
      "pattern": "(?i)\\b(dts[\\s._-]*hd[\\s._-]*ma|dtshd\\s*ma|dts[\\s._-]*hd[\\s._-]*master)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dts_hd_master_audio.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dts-hd",
      "groupId": "audio-tech",
      "name": "DTS-HD",
      "pattern": "(?i)\\b(dts[\\s._-]*hd|dtshd)(?![\\s._-]*(ma|master)|ma)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dts_hd.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "dts",
      "groupId": "audio-tech",
      "name": "DTS",
      "pattern": "(?i)\\bdts\\b(?![\\s._:-]*(x|hd))",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/dts.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "71-audio",
      "groupId": "audio-channels",
      "name": "7.1 Audio",
      "pattern": "(?i)\\b(7\\.1|7-1|8ch|8\\s*channel)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/7_1_audio.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    },
    {
      "id": "51-audio",
      "groupId": "audio-channels",
      "name": "5.1 Audio",
      "pattern": "(?i)\\b(5\\.1|5-1|6ch|6\\s*channel)\\b",
      "imageURL": "https://raw.githubusercontent.com/leonevz/Elite-Badges/main/Badges/5_1_audio.png",
      "tagColor": "#00000000",
      "borderColor": "#00000000",
      "textColor": "#00000000",
      "tagStyle": "filled",
      "isEnabled": true,
      "type": "filter"
    }
  ]
}
